default_context:
  project_name: 'balance'
  project_slug: 'balance'
  domain_main: 'balance.com'
  domain_staging: 'stag.balance.com'
  domain_base_api_url: 'http://balance.com/api/v1'
  domain_base_ws_url: 'ws://balance.com/api/v1'
  docker_swarm_stack_name_main: 'balance-com'
  docker_swarm_stack_name_staging: 'stag-balance-com'
  secret_key: 'qwerty123'
  first_superuser: 'maryartster@gmail.com'
  first_superuser_password: 'qwerty123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.balance.com", "https://stag.balance.com", "https://balance.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@balance.com'
  smtp_emails_from_name: 'M T'
  smtp_emails_to_email: 'maryartster@gmail.com'
  postgres_password: 'qwerty123'
  pgadmin_default_user: 'maryartster@gmail.com'
  pgadmin_default_user_password: 'qwerty123'
  neo4j_password: 'qwerty123'
  traefik_constraint_tag: 'balance.com'
  traefik_constraint_tag_staging: 'stag.balance.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qwerty123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
