name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        python -m venv .venv
        . venv/bin/activate
        cd backend/app/
        poetry install --no-interaction
        cd ../..
    - name: Analysing the code with flake8
      run: |
        flake8 --extend-exclude=/.venv/ --max-line-length=120 backend/app/app/
    - name: Build docker and launch docker app
      run: |
        docker compose -f "docker-compose.yml" up --build -d
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Test with pytest
      run: |
        docker compose exec app sh scripts/test.sh -vv
        coverage report